"""`reflect team ...` subcommands for provisioning and syncing a team KB."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import click
import yaml

TEAM_CONFIG_PATH = Path.home() / ".learnings" / "team-config.yaml"

README_TEMPLATE = """# {name}

Team knowledge base for reflect-kb.

## Structure

- `documents/` — learning notes (`.md` + `.entities.yaml` sidecars)
- `.github/workflows/` — CI validation of frontmatter + schema
- `CODEOWNERS` — category-based review routing
- `.pre-commit-config.yaml` — local schema check before commit

## Contributing

1. Capture learnings via your local reflect CLI (`/reflect` in Claude, skill-
   invocable in Codex/Copilot). HIGH confidence entries land here via PR.
2. Each `.md` requires matching YAML frontmatter (see
   https://github.com/stevengonsalvez/reflect-kb/blob/main/schemas/frontmatter.schema.json).
3. Pre-commit validates the schema locally; CI re-validates on PR.

Generated by `reflect team init`.
"""

PRE_COMMIT_TEMPLATE = """# Auto-generated by `reflect team init`.
# Validates YAML frontmatter on every commit against the reflect-kb schema.
repos:
  - repo: local
    hooks:
      - id: reflect-kb-frontmatter
        name: reflect-kb frontmatter schema
        entry: reflect schema validate
        language: system
        files: '^documents/.*\\.md$'
        pass_filenames: true
"""

CI_WORKFLOW_TEMPLATE = """# Auto-generated by `reflect team init`.
name: validate-frontmatter
on:
  pull_request:
  push:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install 'reflect-kb' 'jsonschema>=4.20' pyyaml
      - run: reflect schema validate documents/
"""

CODEOWNERS_TEMPLATE = """# CODEOWNERS — route review by category.
# Fill in owners once your team KB grows; default assigns to the
# repo maintainer. Categories are keyed off frontmatter `category`,
# resolved at PR-triage time.
*       @REPLACE-ME
"""


def _run_git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    )


def _load_team_config() -> dict:
    if not TEAM_CONFIG_PATH.exists():
        return {}
    return yaml.safe_load(TEAM_CONFIG_PATH.read_text(encoding="utf-8")) or {}


def _save_team_config(cfg: dict) -> None:
    TEAM_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEAM_CONFIG_PATH.write_text(yaml.safe_dump(cfg, sort_keys=True), encoding="utf-8")


def _write_scaffold(root: Path, name: str) -> list[Path]:
    """Create the team-kb skeleton under ``root``. Returns list of created files."""
    created: list[Path] = []
    for sub in ("documents", ".github/workflows"):
        (root / sub).mkdir(parents=True, exist_ok=True)

    files = {
        root / "README.md": README_TEMPLATE.format(name=name),
        root / "CODEOWNERS": CODEOWNERS_TEMPLATE,
        root / ".pre-commit-config.yaml": PRE_COMMIT_TEMPLATE,
        root / ".github/workflows/validate-frontmatter.yml": CI_WORKFLOW_TEMPLATE,
        root / ".gitignore": "nano_graphrag_cache/\n.venv/\n__pycache__/\n",
    }
    for path, content in files.items():
        if path.exists():
            continue
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return created


def _reindex(root: Path) -> None:
    """Best-effort invoke ``reflect reindex`` against ``root`` as the KB root.

    Uses LEARNINGS_DIR env override so reindex operates on the team clone rather
    than the caller's personal ~/.learnings directory.
    """
    env = {**os.environ, "LEARNINGS_DIR": str(root)}
    # Reindex is optional — a freshly scaffolded team has no documents yet,
    # and the nano-graphrag toolchain may be unavailable. Never hard-fail.
    subprocess.run(
        ["reflect", "reindex"],
        cwd=root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


@click.group(name="team")
def team() -> None:
    """Provision, clone, and sync a shared team knowledge base."""


@team.command("init")
@click.argument("path", type=click.Path(file_okay=False, resolve_path=True))
@click.option("--name", default=None, help="Team name (defaults to directory basename).")
def team_init(path: str, name: str | None) -> None:
    """Scaffold a team-kb layout at PATH (documents/, CI, CODEOWNERS, pre-commit)."""
    root = Path(path)
    root.mkdir(parents=True, exist_ok=True)
    created = _write_scaffold(root, name or root.name)

    cfg = _load_team_config()
    cfg["path"] = str(root)
    cfg["name"] = name or root.name
    _save_team_config(cfg)

    click.echo(f"✓ initialized team-kb at {root}")
    for f in created:
        click.echo(f"  + {f.relative_to(root)}")
    if not created:
        click.echo("  (already initialized — no files overwritten)")


@team.command("clone")
@click.argument("url")
@click.option(
    "--path",
    type=click.Path(file_okay=False, resolve_path=True),
    default=None,
    help="Destination (defaults to ~/.learnings/team-<repo>).",
)
@click.option("--no-reindex", is_flag=True, help="Skip index rebuild after clone.")
def team_clone(url: str, path: str | None, no_reindex: bool) -> None:
    """Clone a team-kb URL and rebuild indexes locally."""
    if path is None:
        repo = url.rstrip("/").split("/")[-1].removesuffix(".git")
        path = str(Path.home() / ".learnings" / f"team-{repo}")
    root = Path(path)

    if root.exists() and any(root.iterdir()):
        raise click.ClickException(f"destination {root} exists and is not empty")

    root.parent.mkdir(parents=True, exist_ok=True)
    click.echo(f"cloning {url} → {root} ...")
    subprocess.run(["git", "clone", url, str(root)], check=True)

    cfg = _load_team_config()
    cfg["path"] = str(root)
    cfg["url"] = url
    _save_team_config(cfg)

    if no_reindex:
        click.echo("✓ cloned (reindex skipped)")
        return

    click.echo("rebuilding indexes ...")
    _reindex(root)
    click.echo(f"✓ cloned and indexed: {root}")


@team.command("sync")
@click.option(
    "--path",
    type=click.Path(file_okay=False, resolve_path=True),
    default=None,
    help="Override team path (defaults to configured team).",
)
@click.option("--no-reindex", is_flag=True, help="Skip index rebuild.")
def team_sync(path: str | None, no_reindex: bool) -> None:
    """Pull the team-kb and rebuild indexes if content changed."""
    cfg = _load_team_config()
    resolved = path or cfg.get("path")
    if not resolved:
        raise click.ClickException(
            "no configured team — run `reflect team clone <url>` or `team init <path>` first"
        )
    root = Path(resolved)
    if not root.exists():
        raise click.ClickException(f"configured team path {root} does not exist")
    if not (root / ".git").exists():
        raise click.ClickException(f"{root} is not a git checkout — nothing to sync")

    before = _run_git(["rev-parse", "HEAD"], root).stdout.strip()
    click.echo(f"pulling {root} ...")
    subprocess.run(["git", "-C", str(root), "pull", "--ff-only"], check=True)
    after = _run_git(["rev-parse", "HEAD"], root).stdout.strip()

    if before == after:
        click.echo("✓ already up to date — no reindex needed")
        return
    if no_reindex:
        click.echo(f"✓ synced {before[:8]}..{after[:8]} (reindex skipped)")
        return

    click.echo("content changed — rebuilding indexes ...")
    _reindex(root)
    click.echo(f"✓ synced and reindexed: {before[:8]}..{after[:8]}")
